In [78]:
from sklearn.ensemble import RandomForestClassifier as RF
from sklearn import cross_validation
import numpy as np

X = np.array([[5,5,5,5],[10,10,10,10],[1,1,1,1],[6,6,6,6],[13,13,13,13],[2,2,2,2]])
y = np.array([0,2,1,2,1,2])

In [79]:
X_train, X_test, y_train, y_test = cross_validation.train_test_split(X, y, test_size=0.5, random_state=0)

In [100]:
#http://stats.stackexchange.com/questions/179977/scikit-predict-proba-output-interpretation
clf = RF()
clf.fit(X_train,y_train)
classes = clf.classes_
pred_pro = clf.predict_proba(X_test)
print len(X_test)
print pred_pro
#show the order of the classes in the predicted probability
print classes

3
[[ 0.7  0.   0.3]
 [ 0.7  0.   0.3]
 [ 0.   0.6  0.4]]
[0 1 2]
