In [29]:
#https://docs.mongodb.com/getting-started/python/insert/
import pymongo
from pymongo import MongoClient
from sklearn import datasets
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
import pickle
import json

url = 'mongodb://test1:test1@ds023064.mlab.com:23064/py_log_rec_test1'

client = MongoClient(url)
#client = MongoClient(host='ls021694.mlab.com', port=21694)
db = client.py_log_rec_test1
cursor = db.py_log_rec_test1.find()

print(cursor)

for document in cursor:
    print(document)

In [23]:
#Create data set
data = [[1,1,1,1],[1,1,1,1],[4,4,4,4],[4,4,4,4],[5,5,5,5],[5,5,5,5]]
target = ['one','one','three','three','five','five']

In [24]:
model = LogisticRegression()
model.fit(data, target)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [25]:
expected = target
predicted = model.predict(data)
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))
print(expected)
print(predicted)

             precision    recall  f1-score   support

       five       0.50      1.00      0.67         2
        one       1.00      1.00      1.00         2
      three       0.00      0.00      0.00         2

avg / total       0.50      0.67      0.56         6

[[2 0 0]
 [0 2 0]
 [2 0 0]]
['one', 'one', 'three', 'three', 'five', 'five']
['one' 'one' 'five' 'five' 'five' 'five']


In [30]:
#data = json.dumps(model)

# db.py_log_rec_test1.insert_one(
# {
# "model": model
# }
# )

In [31]:
from pymongo import MongoClient
url = 'mongodb://test1:test1@ds023064.mlab.com:23064/py_log_rec_test1'
client = MongoClient(url)
#database name
db = client.py_log_rec_test1
#collection name
coll = db.test_store_bin_data
# the collection is ready now 
from bson.binary import Binary
import pickle
# create a sample object
myObj = {}
myObj['demo'] = 'Some demo data'
# convert it to the raw bytes
thebytes = pickle.dumps(model)
print(thebytes)
coll.insert({'bin-data': Binary(thebytes)})

ccopy_reg
_reconstructor
p0
(csklearn.linear_model.logistic
LogisticRegression
p1
c__builtin__
object
p2
Ntp3
Rp4
(dp5
S'warm_start'
p6
I00
sS'C'
p7
F1.0
sS'max_iter'
p8
I100
sS'verbose'
p9
I0
sS'intercept_scaling'
p10
I1
sS'dual'
p11
I00
sS'fit_intercept'
p12
I01
sS'classes_'
p13
cnumpy.core.multiarray
_reconstruct
p14
(cnumpy
ndarray
p15
(I0
tp16
S'b'
p17
tp18
Rp19
(I1
(I3
tp20
cnumpy
dtype
p21
(S'S5'
p22
I0
I1
tp23
Rp24
(I3
S'|'
p25
NNNI5
I1
I0
tp26
bI00
S'five\x00one\x00\x00three'
p27
tp28
bsS'solver'
p29
S'liblinear'
p30
sS'n_iter_'
p31
g14
(g15
(I0
tp32
g17
tp33
Rp34
(I1
(I1
tp35
g21
(S'i4'
p36
I0
I1
tp37
Rp38
(I3
S'<'
p39
NNNI-1
I-1
I0
tp40
bI00
S'\x05\x00\x00\x00'
p41
tp42
bsS'penalty'
p43
S'l2'
p44
sS'multi_class'
p45
S'ovr'
p46
sS'random_state'
p47
NsS'tol'
p48
F0.0001
sS'n_jobs'
p49
I1
sS'coef_'
p50
g14
(g15
(I0
tp51
g17
tp52
Rp53
(I1
(I3
I4
tp54
g21
(S'f8'
p55
I0
I1
tp56
Rp57
(I3
S'<'
p58
NNNI-1
I-1
I0
tp59
bI01
S'\xd1}n\xbdV\xd9\xa6?\x9f\xcf\xfe\xff9!\xc8\xbf\xa9}s\x17n\x0

/Users/seth.bunke/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:17: DeprecationWarning: insert is deprecated. Use insert_one or insert_many instead.


ObjectId('576c7d506ea084991c5ab471')

In [39]:
collection = db.test_store_bin_data
m1 = None
for cursor in collection.find({}):
    #print(cursor)
    data = cursor['bin-data']
    #info = pickle.loads(data)
    #print(info)
    m1 = info
    
print(m1)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)


In [40]:
test1 = [[5,5,5,5],[1,1,1,1],[4,4,4,4]]
predicted1 = m1.predict(test1)
print(predicted1)
expected1 = ['five', 'one','two']
print(metrics.classification_report(expected1, predicted1))
print(metrics.confusion_matrix(expected1, predicted1))

['five' 'one' 'five']
             precision    recall  f1-score   support

       five       0.50      1.00      0.67         1
        one       1.00      1.00      1.00         1
        two       0.00      0.00      0.00         1

avg / total       0.50      0.67      0.56         3

[[1 0 0]
 [0 1 0]
 [1 0 0]]
